spring:
  datasource:
    driverClassName : com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservation
    username: root
    password: anshit
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect